### ISSUE TITLE
Add invoke, invokefunction & invokescript RPC methods

### ISSUE THREAD

**Issue by notatestuser** [CityOfZion/neo-js#1]
These were added in v2.3.3 in neo-project/neo@9e904051b17c130f85e539b40712788bf9e08f5d

**Comment by lllwvlvwlll** [comment]
will implement once they have been deployed in production; The current seeds do not support this functionality.

**Comment by notatestuser** [comment]
Do we have a timeline on this and NEP5 support? Kind of need it for the old dApp.

**Comment by lllwvlvwlll** [comment]
Implementation of the new functionality was just released.  They should be available in neo-js in a few days.

**Comment by lllwvlvwlll** [comment]
https://github.com/CityOfZion/neo-js/pull/15

Keep in mind that these rpc calls are only test invokes (they dont get executed on the blockchain).  Will work to add support for blockchain invokes.  This should be available shortly.

**Comment by notatestuser** [comment]
Looking forward to the blockchain invokes!

**Comment by notatestuser** [comment]
@lllwvlvwlll any news on real invokes? if it's just a case of crafting a tx for `sendrawtransaction` I might have a go. Could you confirm what is needed?
