### ISSUE TITLE
Project code refactor proposal

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/neo-js#10]
## Excerpt

This code refactor proposal contains 3 parts, but since they are closely intertwined I decided to have them in the same issue ticket where discussions, suggestions and feedbacks are most welcome.

Shall the community able to reach consensus partially or fully, a developer to be designated on making the refactorization PRs.

## Progress

- [x] uniform code style (following `standard`), mostly aligning spacings
- [ ] ES6 adaptations (this opens up talks for developer's guide and formal system requirements)
- [ ] separation of concerns (relevant to #32), enum pattern, utils/helper classes
- [ ] feature toggle, adaptation of optional parameters and dependencies injection (this may indirectly result in increase of performance)

## Proposals

**1. Language and dependencies:**

1.1. Project to be coded in JavaScript ES6 format + await/async usage.

1.2. No transpilers to be used. Although this will reduce supporting environments, my vote goes toward debuggability and reducing complexity.

1.3. Adapt [Moment](https://github.com/moment/moment) handling datetime related implementations.

**2. System requirements:**

2.1. Minimum Node Node 8+ for async/await support and taking advantage of its [LTS](https://github.com/nodejs/Release).

2.2. Minimum browser requirement is to be browsers that supports [await/async](https://caniuse.com/#search=await). That is: Edge 15+, Firefox 52+, Chrome 55+, Safari 10.1+.

**3. Coding style guide:**

3.1. Follow [JavaScript Standard Style ](https://github.com/standard/standard) as guidance . Developers are recommend to install Standard package globally as Node command line program and perform style checks before submitting PR.

3.2. Allow optional dependency injection of `axios` library. This is the pre-requisite to support unit testing within the project.

3.3. Separate and modularize magic numbers and strings into a static object.

3.4. Expose `axios` and `lodash` and other 3rd party libraries as included utilities. This is to give `neo-js` package users option to utilise these libraries instead of separate reference(s).

**Comment by rockacola** [comment]
Are files are now up to `standard`.

**Comment by rockacola** [comment]
Will proceed with ES6 adaptations and standardisations. `eslint` will be introduced to enforce uniform coding style.

**Comment by sgehrman** [comment]
I was surprised your not using web-pack with eslint, hot-reloading etc.  Code standard should be whatever Atom beautify can do with it's setting since that would keep everyone in sync more easily right?  Just my two cents.
