### ISSUE TITLE
getAssetBalance issue

### ISSUE THREAD

**Issue by danciuc** [CityOfZion/neo-js#162]
There seems to be an issue with balance checking when the address is in the `vin` part of the transaction.

Even though the pull request #161 addresses this, the issue persists if the transaction is not expanded because it doesn't contain the address in this case.
For example, the following `vin` record may refer to the address for which we're trying to get the balance but it will not be returned since there's no address:
```
{
    "vout" : 9998,
    "txid" : "0x3e17f0897f1dcd322476c8c1f5bfd8ac74f3e8d48353b8c87baf7bbcc4783b3f"
}
```

I tried to do a workaround for it by calling `storage.getExpandedTX()` when the transaction is saved to DB but it doesn't work because the save process is async so the referred tx may not be saved yet.

**Comment by rockacola** [comment]
Legacy issue from `<=0.8.1`.
