### ISSUE TITLE
refactor and break out models into separate libraries

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-js#32]
neo.blockchain.db currently contains all the schema and connection information for the full node.

Refactor neo.blockchain.db -> neo.node.storage

Break out the mongoDB model and implementation into its own library(s) which is optionally imported by neo.node.storage based on an input set of options.

**Comment by rockacola** [comment]
I vote for `neo.blockchain.node` splitting itself into `neo.blockchain.node` and `neo.blockchain.rpc` where:
- `neo.blockchain.node` purely responsive for finding/fetching nodes from blockchain. Enhanced feature such as `getHighestNode` should be optional, ie/ it's up to user to decide if they which to have the package constantly hitting `getBlockHeight`.
- `neo.blockchain.rpc` to only deal with JSON-RPC communications.
