### ISSUE TITLE
System asset support

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-js#58]
Code to support asset handling on the blockchain including parsing of the invoke script for relevant metadata

**Comment by rockacola** [comment]
For the asests support, there are the following RPC endpoints we can work with:
* `getRawTransaction()` contains asset transactions.
* `getAccountState()` provides balance summary of all assets per address.
* `getAssetState()` _support_ to provide metadata about a specified asset.

We can create method to support:
* sending of specific asset via invocation with `sendRawTransaction()`.
* list transactions of a specified asset of an address

Does that sound right?

**Comment by lllwvlvwlll** [comment]
for the rpc calls , thats correct.  We'll also want to support this functionality for storage as well (we dont (and shouldnt) need to rely on the rpc calls to get this data when we've already synchronized the blocks

**Comment by rockacola** [comment]
PR #107
