### ISSUE TITLE
deployment of multiple node instances with rpc support for development use

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-js#75]
One of the primary goals of the neo-js project is to implement a network of nodes which enable 'full-node' levels of functionality without synchronizing the entire blockchain.  This task will include the development and deployment of multiple neo-js nodes which expose the functionality of the module via rpc methods.

**Comment by rockacola** [comment]
@lllwvlvwlll, I would like to propose pushing this to `0.8.0` release.

**Comment by rockacola** [comment]
Legacy issue from `<=0.8.1`.
