### ISSUE TITLE
dynamic seed registration rpc method

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-js#76]
Extension of core rpc methods to enable dynamic node registration. 

This method will be invoked with inputs containing the requestor's contact information as its configuration information (what type of node it is etc..)

When invoked, this method should return a dump off all the nodes that the node instance is tracking with their most recent states. This information will be used to integrate a new node into the mesh.

**Comment by lllwvlvwlll** [comment]
@rockacola This issue has not been resolved.  Optional node inputs are a separate functionality.

**Comment by rockacola** [comment]
@lllwvlvwlll are there more to this case than what's been implemented in PR #98 ? Can you elaborate? Thank you.
