### ISSUE TITLE
Getting error: neo is not a function

### ISSUE THREAD

**Issue by hahahatrick** [CityOfZion/neo-js#79]
I followed the instructions:

`var neo = require('neo-js-blockchain');
var neoBlockchain = neo('full', 'mainnet');`

I'm getting error:

`TypeError: neo is not a function
    at Object.<anonymous> (/home/NEO/index.js:2:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

Please help.

Thank you.

**Comment by tsirolnik** [comment]
Seems like the README is wrong as the module exports { neo: Object } and not itself...

So, the following would work - 
```js
const Neo = require('neo-js-blockchain').neo; 
let neoBlockchain = new Neo('full', 'mainnet');
```

**Comment by professorhantzen** [comment]
Also, after doing that you may run into an additional issue I had. When installing via npm, dist/neo.blockchain.node.js had a couple of missing colons after "params" that prevented the module for working. (This was a couple of days ago, maybe it's been fixed.)

**Comment by hahahatrick** [comment]
@tsirolnik That worked! thanks.

@professorhantzen Yes. Its not yet fixed.

**Comment by tsirolnik** [comment]
@professorhantzen I have the same issue

``
neo-js-blockchain/dist/neo.blockchain.node.js:366
params[scriptHash, params],
           ^

Syntax Error: Unexpected token [ 
``

@hahahatrick You're welcome

**Comment by tsirolnik** [comment]
Seems like the npm package is outdated and full of bugs for some reason...

Clone the repo and use it instead

**Comment by tsirolnik** [comment]
@lllwvlvwlll Could you re-upload the npm package?

**Comment by lllwvlvwlll** [comment]
We are going to expedite release of 0.5 to fix these issues.  We will try to get it out tonight.  Please keep in mind that some of the syntax will be changing.

**Comment by lllwvlvwlll** [comment]
Please reference the latest version and documentation (0.5.0)
