### ISSUE TITLE
Would anyone of you make a tutorial for beginners

### ISSUE THREAD

**Issue by dadmor** [CityOfZion/neo-js#82]
Step by step from npm install to realize smart contract with screens?

**Comment by rockacola** [comment]
We are picking up momentum on both features and documentations, a stable release should be ready within days.

As for now, you may be better off checking out `develop` branch:

* https://github.com/CityOfZion/neo-js/tree/develop

Or reference to GitHub directly in NPM:

```
npm install --save CityOfZion/neo-js#develop
```

**Comment by lllwvlvwlll** [comment]
@slipo

**Comment by rockacola** [comment]
We are not likely to reach to tutorial stage until we are close to `version 1`.

Close issue for the time being.
