### ISSUE TITLE
Ability to connect to private blockchain networks

### ISSUE THREAD

**Issue by slipo** [CityOfZion/neo-js#83]
Should work with this:
https://github.com/CityOfZion/neo-privatenet-docker

**Comment by rockacola** [comment]
Base on my understanding, there's lack of RPC API in private net. @birmas can you share your experience so far?

Otherwise, there is (undocumented) plan to be able to inject endpoints replacing its default list.

**Comment by rockacola** [comment]
Evaluated as feature request #97
